/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

dependencies {
    implementation(KOTLIN_BOM)

    implementation(KOTLIN_STDLIB_JDK8)
    implementation(GUAVA)

    testImplementation(KOTLIN_TEST)
    testImplementation(KOTLIN_TEST_JUNIT)
    implementation(kotlin("stdlib-jdk8"))
}

application {
    // Define the main class for the application.
    mainClass.set("how.kot.works.AppKt")
}